# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 05 Dec 2013 06:54:31 +0000
*               @ALL          1
*               @user         8
wiki:welcome	@user	0
sidebar	@user	0
