<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: caijun
 * Date: Mon, 09 Dec 2013 15:10:55 +0000
 */

$conf['title'] = '菜菜的百科全书';
$conf['lang'] = 'zh';
$conf['template'] = 'arctic';
$conf['license'] = 'cc-by-sa';
$conf['youarehere'] = 1;
$conf['useheading'] = 'navigation';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['updatecheck'] = 0;
$conf['plugin']['tag']['toolbar_icon'] = 1;
$conf['tpl']['arctic']['right_sidebar_content'] = 'main,toc,user,group,namespace,toolbox,index,trace,extra';

// end auto-generated content
